# Generated by Django 4.0.6 on 2022-07-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultCompany',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128)),
                ('account_name', models.CharField(max_length=128, null=True)),
                ('created_at', models.CharField(max_length=128, null=True)),
                ('description', models.TextField(null=True)),
                ('location', models.CharField(max_length=128, null=True)),
                ('pinned_tweet_id', models.TextField(null=True)),
                ('url', models.TextField(null=True)),
                ('followers_count', models.IntegerField(null=True)),
                ('following_count', models.IntegerField(null=True)),
                ('tweet_count', models.IntegerField(null=True)),
                ('listed_count', models.IntegerField(null=True)),
                ('verified', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultTweet',
            fields=[
                ('author_id', models.IntegerField()),
                ('tweet_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(null=True)),
                ('created_at', models.CharField(max_length=128, null=True)),
                ('retweets', models.IntegerField(null=True)),
                ('replies', models.IntegerField(null=True)),
                ('likes', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicCompany',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128)),
                ('account_name', models.CharField(max_length=128, null=True)),
                ('created_at', models.CharField(max_length=128, null=True)),
                ('description', models.TextField(null=True)),
                ('location', models.CharField(max_length=128, null=True)),
                ('pinned_tweet_id', models.TextField(null=True)),
                ('url', models.TextField(null=True)),
                ('followers_count', models.IntegerField(null=True)),
                ('following_count', models.IntegerField(null=True)),
                ('tweet_count', models.IntegerField(null=True)),
                ('listed_count', models.IntegerField(null=True)),
                ('verified', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicTweet',
            fields=[
                ('author_id', models.IntegerField()),
                ('tweet_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(null=True)),
                ('created_at', models.CharField(max_length=128, null=True)),
                ('retweets', models.IntegerField(null=True)),
                ('replies', models.IntegerField(null=True)),
                ('likes', models.IntegerField(null=True)),
            ],
        ),
    ]
